name: Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Get commit hash
        run: echo "COMMIT_HASH=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_SKILLFY }}
          username: ${{ secrets.USER_SKILLFY }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            # Atualizar a imagem Docker
            docker pull jieffcavalcanti/nest:$COMMIT_HASH

            # Parar e remover o contêiner existente
            docker stop $COMMIT_HASH || true
            docker rm $COMMIT_HASH || true

            # Iniciar um novo contêiner com o nome do commit e a imagem atualizada
            docker run -d --name $COMMIT_HASH -p 5000:3000 jieffcavalcanti/nest:$COMMIT_HASH
